SELECT
	R.DEMAND_LEVEL,
	E.VARIANT,
	COUNT(*) AS EVENTS,
	ROUND(AVG(E.RIDE_COMPLETED) * 100, 2) AS COMPLETION_RATE_PRCT,
	ROUND(AVG(E.WAIT_TIME_MINUTES), 2) AS AVERAGE_WAIT_TIME
FROM
	EXPERIMENT_EVENTS E
	JOIN USERS U ON E.USER_ID = U.USER_ID
	JOIN REGIONS R ON U.REGION_ID = R.REGION_ID
GROUP BY
	R.DEMAND_LEVEL,
	E.VARIANT
ORDER BY
	R.DEMAND_LEVEL,
	E.VARIANT