
CREATE TABLE EXPERIMENTS (
	EXPERIMENT_ID INT PRIMARY KEY,
	EXPERIMENT_NAME TEXT,
	START_DATE DATE,
	END_DATE DATE
);

CREATE TABLE REGIONS (
	REGION_ID INT PRIMARY KEY,
	REGION_NAME TEXT,
	DEMAND_LEVEL TEXT -- 'Low', 'Medium', 'High'
);

CREATE TABLE USERS (
	USER_ID INT PRIMARY KEY,
	REGION_ID INT REFERENCES REGIONS (REGION_ID)
);

CREATE TABLE EXPERIMENT_EVENTS (
	EVENT_ID INT PRIMARY KEY,
	EXPERIMENT_ID INT REFERENCES EXPERIMENTS (EXPERIMENT_ID),
	USER_ID INT REFERENCES USERS (USER_ID),
	VARIANT CHAR(1), -- A or B
	RIDE_REQUESTED INT, -- 1 = yes
	RIDE_COMPLETED INT, -- 1 = completed
	WAIT_TIME_MINUTES INT, -- time to vehicle
	REVENUE NUMERIC(10, 2),
	EVENT_DATE DATE
);